# Generated by Django 4.0.6 on 2022-08-02 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mangas',
            new_name='Manga',
        ),
    ]
